### PR TITLE
remove link to "official guide" before 5min instruction - fixes #41

### LINKED ISSUE #41: Reference "Official guide" _after_ DWYL's 5 minute guide
Because of the ordering on the how section
> ## How?
> The best place to start is with the "_Official Guide_": http://guide.elm-lang.org/get_started.html <br />
we have _condensed_ the steps into the **5-minute** instructions below:

I think people are quite likely to click on the link and start working through the installation guide, before even reading "we have condensed the steps below" - something I see really often when people are going through online tutorials.

If you think it is better/easier for people to follow DWYL's condensed version (which I definitely do), I would suggest you change the order, so that you reference the official guide at the end

### PR DESCRIPTION
**Pull request by jsms90**

### CODE REVIEW

**Comment by iteles** [comment]
:heart: Thanks for putting in the time to create this PR @jsms90 !

**Comment by iteles** [comment]
P.s. we're making a bunch of improvements to our contributing guide and you might find it clearer now: https://github.com/dwyl/contributing#pull-requests

**Comment by jsms90** [comment]
@iteles Haha, that's ok. It only took 5 mins :sweat_smile:

**Comment by jsms90** [comment]
Should the issue have been in user story format?

Also, the `in-progress` and `in-review` labels & "READY FOR REVIEW" seemed a bit overkill for such a small, non-coding change. Is all of that only intended for code related PRs?

Whatever helps, in terms of documenting alterations :+1:

**Pull request merged**
