### PR TITLE
added fizzbuzz example

### PR DESCRIPTION
**Pull request by gabrielperales**
I hope this can be helpful... but I'll need some help checking grammars in my explanations 😅

### CODE REVIEW

**Comment by lucymonie** [comment]
First of all, I have low confidence in the validity of this comment but it looks from the code as though you are expecting the code to render onscreen as an unordered list (if you run elm-reactor). When I did this, I saw an error. What this what you were expecting @gabrielperales? Is it purely a code example, or is it meant to display the list?

**Comment by gabrielperales** [comment]
@lucymonie it should render this list:

captura de pantalla 2017-02-05 a las 18 51 11

Which error are you getting?

**Comment by lucymonie** [comment]
@gabrielperales, I'm getting `elm-make: Map.!: given key is not an element in the map`

**Comment by lucymonie** [comment]
I ran npm install multiple times and then it worked. Merging now.

**Pull request merged**
